"""Add extended user profile fields

Revision ID: 20340a6e3aef
Revises: e4b2d835ced0
Create Date: 2025-04-11 16:16:30.650314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20340a6e3aef'
down_revision = 'e4b2d835ced0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
