"""Add new Conversation_context

Revision ID: 5658b5f76dba
Revises: 20340a6e3aef
Create Date: 2025-04-16 10:14:28.184008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5658b5f76dba'
down_revision = '20340a6e3aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_context', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_room', schema=None) as batch_op:
        batch_op.drop_column('conversation_context')

    # ### end Alembic commands ###
